// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: data_point_list_response.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Com.Cognite.V1.Timeseries.Proto {

  /// <summary>Holder for reflection information generated from data_point_list_response.proto</summary>
  public static partial class DataPointListResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for data_point_list_response.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DataPointListResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5kYXRhX3BvaW50X2xpc3RfcmVzcG9uc2UucHJvdG8SH2NvbS5jb2duaXRl",
            "LnYxLnRpbWVzZXJpZXMucHJvdG8aEWRhdGFfcG9pbnRzLnByb3RvIrkCChFE",
            "YXRhUG9pbnRMaXN0SXRlbRIKCgJpZBgBIAEoAxISCgpleHRlcm5hbElkGAIg",
            "ASgJEk8KEW51bWVyaWNEYXRhcG9pbnRzGAMgASgLMjIuY29tLmNvZ25pdGUu",
            "djEudGltZXNlcmllcy5wcm90by5OdW1lcmljRGF0YXBvaW50c0gAEk0KEHN0",
            "cmluZ0RhdGFwb2ludHMYBCABKAsyMS5jb20uY29nbml0ZS52MS50aW1lc2Vy",
            "aWVzLnByb3RvLlN0cmluZ0RhdGFwb2ludHNIABJTChNhZ2dyZWdhdGVEYXRh",
            "cG9pbnRzGAUgASgLMjQuY29tLmNvZ25pdGUudjEudGltZXNlcmllcy5wcm90",
            "by5BZ2dyZWdhdGVEYXRhcG9pbnRzSABCDwoNZGF0YXBvaW50VHlwZSJaChVE",
            "YXRhUG9pbnRMaXN0UmVzcG9uc2USQQoFaXRlbXMYASADKAsyMi5jb20uY29n",
            "bml0ZS52MS50aW1lc2VyaWVzLnByb3RvLkRhdGFQb2ludExpc3RJdGVtQgJQ",
            "AWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Com.Cognite.V1.Timeseries.Proto.DataPointsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Cognite.V1.Timeseries.Proto.DataPointListItem), global::Com.Cognite.V1.Timeseries.Proto.DataPointListItem.Parser, new[]{ "Id", "ExternalId", "NumericDatapoints", "StringDatapoints", "AggregateDatapoints" }, new[]{ "DatapointType" }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Cognite.V1.Timeseries.Proto.DataPointListResponse), global::Com.Cognite.V1.Timeseries.Proto.DataPointListResponse.Parser, new[]{ "Items" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class DataPointListItem : pb::IMessage<DataPointListItem> {
    private static readonly pb::MessageParser<DataPointListItem> _parser = new pb::MessageParser<DataPointListItem>(() => new DataPointListItem());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DataPointListItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Cognite.V1.Timeseries.Proto.DataPointListResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DataPointListItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DataPointListItem(DataPointListItem other) : this() {
      id_ = other.id_;
      externalId_ = other.externalId_;
      switch (other.DatapointTypeCase) {
        case DatapointTypeOneofCase.NumericDatapoints:
          NumericDatapoints = other.NumericDatapoints.Clone();
          break;
        case DatapointTypeOneofCase.StringDatapoints:
          StringDatapoints = other.StringDatapoints.Clone();
          break;
        case DatapointTypeOneofCase.AggregateDatapoints:
          AggregateDatapoints = other.AggregateDatapoints.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DataPointListItem Clone() {
      return new DataPointListItem(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "externalId" field.</summary>
    public const int ExternalIdFieldNumber = 2;
    private string externalId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ExternalId {
      get { return externalId_; }
      set {
        externalId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "numericDatapoints" field.</summary>
    public const int NumericDatapointsFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Com.Cognite.V1.Timeseries.Proto.NumericDatapoints NumericDatapoints {
      get { return datapointTypeCase_ == DatapointTypeOneofCase.NumericDatapoints ? (global::Com.Cognite.V1.Timeseries.Proto.NumericDatapoints) datapointType_ : null; }
      set {
        datapointType_ = value;
        datapointTypeCase_ = value == null ? DatapointTypeOneofCase.None : DatapointTypeOneofCase.NumericDatapoints;
      }
    }

    /// <summary>Field number for the "stringDatapoints" field.</summary>
    public const int StringDatapointsFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Com.Cognite.V1.Timeseries.Proto.StringDatapoints StringDatapoints {
      get { return datapointTypeCase_ == DatapointTypeOneofCase.StringDatapoints ? (global::Com.Cognite.V1.Timeseries.Proto.StringDatapoints) datapointType_ : null; }
      set {
        datapointType_ = value;
        datapointTypeCase_ = value == null ? DatapointTypeOneofCase.None : DatapointTypeOneofCase.StringDatapoints;
      }
    }

    /// <summary>Field number for the "aggregateDatapoints" field.</summary>
    public const int AggregateDatapointsFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Com.Cognite.V1.Timeseries.Proto.AggregateDatapoints AggregateDatapoints {
      get { return datapointTypeCase_ == DatapointTypeOneofCase.AggregateDatapoints ? (global::Com.Cognite.V1.Timeseries.Proto.AggregateDatapoints) datapointType_ : null; }
      set {
        datapointType_ = value;
        datapointTypeCase_ = value == null ? DatapointTypeOneofCase.None : DatapointTypeOneofCase.AggregateDatapoints;
      }
    }

    private object datapointType_;
    /// <summary>Enum of possible cases for the "datapointType" oneof.</summary>
    public enum DatapointTypeOneofCase {
      None = 0,
      NumericDatapoints = 3,
      StringDatapoints = 4,
      AggregateDatapoints = 5,
    }
    private DatapointTypeOneofCase datapointTypeCase_ = DatapointTypeOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DatapointTypeOneofCase DatapointTypeCase {
      get { return datapointTypeCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearDatapointType() {
      datapointTypeCase_ = DatapointTypeOneofCase.None;
      datapointType_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DataPointListItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DataPointListItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (ExternalId != other.ExternalId) return false;
      if (!object.Equals(NumericDatapoints, other.NumericDatapoints)) return false;
      if (!object.Equals(StringDatapoints, other.StringDatapoints)) return false;
      if (!object.Equals(AggregateDatapoints, other.AggregateDatapoints)) return false;
      if (DatapointTypeCase != other.DatapointTypeCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (ExternalId.Length != 0) hash ^= ExternalId.GetHashCode();
      if (datapointTypeCase_ == DatapointTypeOneofCase.NumericDatapoints) hash ^= NumericDatapoints.GetHashCode();
      if (datapointTypeCase_ == DatapointTypeOneofCase.StringDatapoints) hash ^= StringDatapoints.GetHashCode();
      if (datapointTypeCase_ == DatapointTypeOneofCase.AggregateDatapoints) hash ^= AggregateDatapoints.GetHashCode();
      hash ^= (int) datapointTypeCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (ExternalId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ExternalId);
      }
      if (datapointTypeCase_ == DatapointTypeOneofCase.NumericDatapoints) {
        output.WriteRawTag(26);
        output.WriteMessage(NumericDatapoints);
      }
      if (datapointTypeCase_ == DatapointTypeOneofCase.StringDatapoints) {
        output.WriteRawTag(34);
        output.WriteMessage(StringDatapoints);
      }
      if (datapointTypeCase_ == DatapointTypeOneofCase.AggregateDatapoints) {
        output.WriteRawTag(42);
        output.WriteMessage(AggregateDatapoints);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (ExternalId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ExternalId);
      }
      if (datapointTypeCase_ == DatapointTypeOneofCase.NumericDatapoints) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NumericDatapoints);
      }
      if (datapointTypeCase_ == DatapointTypeOneofCase.StringDatapoints) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(StringDatapoints);
      }
      if (datapointTypeCase_ == DatapointTypeOneofCase.AggregateDatapoints) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AggregateDatapoints);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DataPointListItem other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.ExternalId.Length != 0) {
        ExternalId = other.ExternalId;
      }
      switch (other.DatapointTypeCase) {
        case DatapointTypeOneofCase.NumericDatapoints:
          if (NumericDatapoints == null) {
            NumericDatapoints = new global::Com.Cognite.V1.Timeseries.Proto.NumericDatapoints();
          }
          NumericDatapoints.MergeFrom(other.NumericDatapoints);
          break;
        case DatapointTypeOneofCase.StringDatapoints:
          if (StringDatapoints == null) {
            StringDatapoints = new global::Com.Cognite.V1.Timeseries.Proto.StringDatapoints();
          }
          StringDatapoints.MergeFrom(other.StringDatapoints);
          break;
        case DatapointTypeOneofCase.AggregateDatapoints:
          if (AggregateDatapoints == null) {
            AggregateDatapoints = new global::Com.Cognite.V1.Timeseries.Proto.AggregateDatapoints();
          }
          AggregateDatapoints.MergeFrom(other.AggregateDatapoints);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            ExternalId = input.ReadString();
            break;
          }
          case 26: {
            global::Com.Cognite.V1.Timeseries.Proto.NumericDatapoints subBuilder = new global::Com.Cognite.V1.Timeseries.Proto.NumericDatapoints();
            if (datapointTypeCase_ == DatapointTypeOneofCase.NumericDatapoints) {
              subBuilder.MergeFrom(NumericDatapoints);
            }
            input.ReadMessage(subBuilder);
            NumericDatapoints = subBuilder;
            break;
          }
          case 34: {
            global::Com.Cognite.V1.Timeseries.Proto.StringDatapoints subBuilder = new global::Com.Cognite.V1.Timeseries.Proto.StringDatapoints();
            if (datapointTypeCase_ == DatapointTypeOneofCase.StringDatapoints) {
              subBuilder.MergeFrom(StringDatapoints);
            }
            input.ReadMessage(subBuilder);
            StringDatapoints = subBuilder;
            break;
          }
          case 42: {
            global::Com.Cognite.V1.Timeseries.Proto.AggregateDatapoints subBuilder = new global::Com.Cognite.V1.Timeseries.Proto.AggregateDatapoints();
            if (datapointTypeCase_ == DatapointTypeOneofCase.AggregateDatapoints) {
              subBuilder.MergeFrom(AggregateDatapoints);
            }
            input.ReadMessage(subBuilder);
            AggregateDatapoints = subBuilder;
            break;
          }
        }
      }
    }

  }

  public sealed partial class DataPointListResponse : pb::IMessage<DataPointListResponse> {
    private static readonly pb::MessageParser<DataPointListResponse> _parser = new pb::MessageParser<DataPointListResponse>(() => new DataPointListResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DataPointListResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Cognite.V1.Timeseries.Proto.DataPointListResponseReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DataPointListResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DataPointListResponse(DataPointListResponse other) : this() {
      items_ = other.items_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DataPointListResponse Clone() {
      return new DataPointListResponse(this);
    }

    /// <summary>Field number for the "items" field.</summary>
    public const int ItemsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Com.Cognite.V1.Timeseries.Proto.DataPointListItem> _repeated_items_codec
        = pb::FieldCodec.ForMessage(10, global::Com.Cognite.V1.Timeseries.Proto.DataPointListItem.Parser);
    private readonly pbc::RepeatedField<global::Com.Cognite.V1.Timeseries.Proto.DataPointListItem> items_ = new pbc::RepeatedField<global::Com.Cognite.V1.Timeseries.Proto.DataPointListItem>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Com.Cognite.V1.Timeseries.Proto.DataPointListItem> Items {
      get { return items_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DataPointListResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DataPointListResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!items_.Equals(other.items_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= items_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      items_.WriteTo(output, _repeated_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += items_.CalculateSize(_repeated_items_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DataPointListResponse other) {
      if (other == null) {
        return;
      }
      items_.Add(other.items_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            items_.AddEntriesFrom(input, _repeated_items_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
